Feature/admin panel
xevyd/TaskManager pull request #14
Opened 2020-05-11 21:44 UTC by xevyd

2020-05-12 19:22 UTC, pn-y requested changes

2020-05-12 19:22 UTC, pn-y commented on test/controllers/admin_controller_test.rb
> +    assert_response :redirect
Надо проверить суть операции, а не просто редирект

2020-05-12 19:22 UTC, pn-y commented on test/controllers/admin_controller_test.rb
> +    assert_response :redirect
Надо проверить суть операции, а не просто редирект

2020-05-12 19:22 UTC, pn-y commented on test/controllers/admin_controller_test.rb
> +    assert_response :redirect
Надо проверить суть операции, а не просто редирект

2020-05-12 19:22 UTC, pn-y commented on config/puma.rb
> +bind 'tcp://0.0.0.0:8080'
А это точно надо?

2020-05-13 07:18 UTC, xevyd commented on config/puma.rb
> +bind 'tcp://0.0.0.0:8080'
это делает сервер доступным при запуске контейнера через `docker-compose run`, а не только через `docker-compose up`. в первом случае без этого сервер будет доступен только внутри контейнера (Listening on tcp://127.0.0.1:3000), но не из вне (Listening on tcp://0.0.0.0:8080)

2020-05-13 12:35 UTC, xevyd commented on test/controllers/admin_controller_test.rb
> +    assert_response :redirect
поправил тесты

2020-05-13 17:33 UTC, pn-y requested changes

2020-05-13 17:33 UTC, pn-y commented on test/controllers/admin_controller_test.rb
> +    assert User.find_by(first_name: user[:first_name]).present?
лучше разделять поиск и использование. 
Допустим тебе понадобится не только first_name проверить, но и еще один атрибут. 
Не понятен профит от таког сокращения. 
А еще ты уверен что искать по first_name это хорошая идея? Они же у тебя не уникальны.

2020-05-13 17:33 UTC, pn-y commented on test/controllers/admin_controller_test.rb
> +    assert User.find(user.id)[:first_name] == user_attrs[:first_name]
тот же коммент что и сверху

2020-05-13 17:33 UTC, pn-y commented on test/factories/sequences.rb
> +  sequence :name, aliases: [:first_name, :last_name, :description, :author, :assignee] do |n|
:author :assignee будто бы абсолютно не место здесь. Это же не строки

2020-05-13 18:22 UTC, pn-y requested changes

2020-05-13 18:22 UTC, pn-y commented on test/controllers/admin_controller_test.rb
> +    user = attributes_for(:user)
Вот читаю... user =... хешу!
Хеш эт не юзер :(
Надо поработать над именованием

2020-05-13 18:22 UTC, pn-y commented on test/controllers/admin_controller_test.rb
> +    user_in_db = User.find(user.id)[:email]
user_in_db... а это строка с емейлом.
Аттрибуты не стоит брать через синтаксис хеша.

2020-05-13 18:22 UTC, pn-y commented on test/controllers/admin_controller_test.rb
> +    assert_not User.exists?(user.id)
👍

2020-05-13 18:25 UTC, mkalmykov requested changes

2020-05-13 18:25 UTC, mkalmykov commented on test/controllers/admin_controller_test.rb
> +    user_in_db = User.find_by(email: user[:email])
`created_user` -- более семантичное название.

2020-05-13 18:25 UTC, mkalmykov commented on test/controllers/admin_controller_test.rb
> +    user = attributes_for(:user)
Лучше назвать переменную `user_attributes`.

2020-05-13 18:25 UTC, mkalmykov commented on test/controllers/admin_controller_test.rb
> +    assert user_in_db.present?
Кроме того, что юзер создался, неплохо бы ещё проверить его атрибуты на совпадение с ожидаемыми.

2020-05-13 18:25 UTC, mkalmykov commented on test/controllers/admin_controller_test.rb
> +    assert user_in_db == user_attrs[:email]
Лучше протестировать полный набор атрибутов.

2020-05-13 18:25 UTC, mkalmykov commented on test/controllers/admin_controller_test.rb
> +    assert_not User.exists?(user.id)
Точно тест проходит? Не припоминаю метода `assert_not`. Для отрицания обычно `refute`.

2020-05-13 18:25 UTC, mkalmykov commented on test/factories/users.rb
> -    factory :admin do
На мой взгляд наследование фабрик лучше, чем дублирование.

2020-05-13 18:37 UTC, xevyd commented on test/controllers/admin_controller_test.rb
> +    assert_not User.exists?(user.id)
проходит. вот здесь в спецификациях он есть - http://rusrails.ru/a-guide-to-testing-rails-applications#dostupnye-utverzhdeniya

2020-05-14 11:18 UTC, xevyd commented on test/factories/users.rb
> -    factory :admin do
возможно, я что-то делаю неправильно, но при наследовании возникает 403 ошибка

2020-05-14 13:02 UTC, xevyd commented on test/factories/users.rb
> -    factory :admin do
поправил

2020-05-14 20:10 UTC, pn-y approved these changes

2020-05-15 06:56 UTC, merged