Feature/api
xevyd/TaskManager pull request #15
Opened 2020-05-15 12:07 UTC by xevyd

2020-05-15 14:57 UTC, pn-y requested changes

2020-05-15 14:57 UTC, pn-y commented on app/controllers/api/v1/tasks_controller.rb
> +    tasks = Task.all.
`all` не требуется

2020-05-15 15:20 UTC, xevyd commented on app/controllers/api/v1/tasks_controller.rb
> +    tasks = Task.all.
убрал

2020-05-15 18:43 UTC, artempartos requested changes

2020-05-15 18:43 UTC, artempartos commented on test/factories/tasks.rb
>      author factory: :manager
давай по умолчанию сделаем ассоциации пустыми (это со временем вызовет циклическое создание ассоциаций), и сделаем trait если где нужен task с ассоциацией

2020-05-16 06:30 UTC, xevyd commented on test/factories/tasks.rb
>      author factory: :manager
сделал

2020-05-16 12:10 UTC, pn-y approved these changes

2020-05-16 12:12 UTC, merged