Feature/tasks
xevyd/TaskManager pull request #17
Opened 2020-06-01 13:14 UTC by xevyd

2020-06-01 20:02 UTC, pn-y requested changes

2020-06-01 20:02 UTC, pn-y commented on config/initializers/kaminari_config.rb
> +  # config.outer_window = 0
remove comments

2020-06-01 20:02 UTC, pn-y commented on app/javascript/packs/components/ColumnHeader/ColumnHeader.js
> +          <IconButton aria-label="Load more" onClick={() => handleLoadMore()}>
onClick={handeLoadMore}

2020-06-01 20:50 UTC, xevyd commented on app/javascript/packs/components/ColumnHeader/ColumnHeader.js
> +          <IconButton aria-label="Load more" onClick={() => handleLoadMore()}>
done

2020-06-02 10:10 UTC, pn-y requested changes

2020-06-02 10:10 UTC, pn-y commented on app/javascript/forms/TaskForm.js
> +      authorId: propOr(null, 'id', task.author),
можно менять автора?

2020-06-02 10:30 UTC, xevyd commented on app/javascript/forms/TaskForm.js
> +      authorId: propOr(null, 'id', task.author),
нельзя. убрать отсюда?

2020-06-02 12:30 UTC, xevyd commented on app/javascript/forms/TaskForm.js
> +      authorId: propOr(null, 'id', task.author),
это было взято из задания. посмотрел следующую часть. в ней и появляется возможность менять автора, я так понимаю

2020-06-03 10:58 UTC, pn-y commented on app/javascript/forms/TaskForm.js
> +      authorId: propOr(null, 'id', task.author),
Нет, там пример на авторе.. но менять assignee :)

2020-06-03 15:03 UTC, xevyd commented on app/javascript/forms/TaskForm.js
> +      authorId: propOr(null, 'id', task.author),
удалил

2020-06-04 10:16 UTC, pn-y approved these changes

2020-06-04 10:18 UTC, merged