Feature/assignee
xevyd/TaskManager pull request #18
Opened 2020-06-05 11:50 UTC by xevyd

2020-06-05 12:09 UTC, pn-y requested changes

2020-06-05 12:09 UTC, pn-y commented on app/javascript/packs/components/Form/Form.js
> +        value={task.author}
презентер потерялся

2020-06-06 18:53 UTC, helmq approved these changes

2020-06-06 20:13 UTC, merged

2020-06-07 07:43 UTC, vdv73rus commented on app/javascript/repositories/UsersRepository.js
> +  show(id) {
Не нашёл использования этого метода, он точно нужен в коде?

2020-06-08 06:24 UTC, xevyd commented on app/javascript/repositories/UsersRepository.js
> +  show(id) {
это для приведения в соответствие с backend. там такой метод реализован, и здесь я подумал тоже было бы логично его реализовать