gen models
xevyd/TaskManager pull request #2
Opened 2020-05-02 09:17 UTC by xevyd

2020-05-04 17:00 UTC, Andrew8xx8 requested changes

2020-05-04 17:00 UTC, Andrew8xx8 commented on test/models/admin_test.rb
> +class AdminTest < ActiveSupport::TestCase
Пустые тесты надо удалить

2020-05-05 06:49 UTC, xevyd commented on test/models/admin_test.rb
> +class AdminTest < ActiveSupport::TestCase
удалил

2020-05-06 10:59 UTC, Andrew8xx8 requested changes

2020-05-06 10:59 UTC, Andrew8xx8 commented on test/factories/tasks.rb
> +FactoryBot.define do
В фабриках нужно использовать генерацию значений. Об этом добавился параграф в обучении, продублирую его сюда

```
В процессе генерации моделей для каждой создалась фабрика. Фабрики используются для генерации тестовых данных. Смысл их в том, что каждый раз при создании моделей в тестах, будет сгенерировано уникальное значение, для этого используется счетчик. Автоматически сгенерированные фабрики содержат статические значения, их необходимо заменить на динамически генерируемые, используя sequence.

Как это сделать: https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#sequences
```

2020-05-07 13:01 UTC, xevyd commented on test/factories/tasks.rb
> +FactoryBot.define do
добавил фабрики

2020-05-07 13:47 UTC, Andrew8xx8 requested changes

2020-05-07 13:47 UTC, Andrew8xx8 commented on test/factories/users.rb
> +    type { '' }
Пустой тип. Не должно быть его, можно убрать совсем, чтобы не задавать пустое значение

2020-05-07 13:47 UTC, Andrew8xx8 commented on test/factories/sequences.rb
> +  factory :admin do
Этот код — это не sequence, а фабрика 

Ты не правильно понял nested в factory_bot. ПОсмотри еще раз в документации. Таким образом у тебя не будет работать наследование фабрик, потому что factory :admin не вложено в юзера

2020-05-07 13:57 UTC, xevyd commented on test/factories/sequences.rb
> +  factory :admin do
спасибо. посмотрел еще раз. поправил.

2020-05-07 14:18 UTC, pn-y requested changes

2020-05-07 14:18 UTC, pn-y commented on test/factories/tasks.rb
> +    author_id
Не стоит работать с ассоциациями как с айдишниками, если этого можно избежать.
Не стоит так же создавать ассоциации безусловно. Это в итоге приведет к снежному кому при тестах - они начнут работать медленно и не факт что стабильно. Создай отдельные трейты для тех случаев когда тебе нужны таски с assignee и с автором

2020-05-07 14:38 UTC, xevyd commented on test/factories/tasks.rb
> +    author_id
сделал отдельно

2020-05-07 15:13 UTC, pn-y requested changes

2020-05-07 15:13 UTC, pn-y commented on test/factories/tasks.rb
> +      author_id
Ты не должен хотеть манипулировать айдишниками ассоциаций

2020-05-07 15:17 UTC, xevyd commented on test/factories/tasks.rb
> +      author_id
вот это я вообще не понял

2020-05-07 22:08 UTC, Andrew8xx8 approved these changes

2020-05-08 06:10 UTC, merged