Feature/mailer
xevyd/TaskManager pull request #25
Opened 2020-06-21 11:19 UTC by xevyd

2020-06-21 11:38 UTC, pn-y requested changes
Прям хорошо, мне понравилось

2020-06-21 11:38 UTC, pn-y commented on app/controllers/web/passwords_controller.rb
> +      @user.send_password_reset_email
Как правило отправка писем это не ответственность модели. В данном случае кмк даже лучше будет отправить письмо прям из контроллера

2020-06-21 11:38 UTC, pn-y commented on app/controllers/web/passwords_controller.rb
> +    @user = User.find_by_password_reset_token(params[:token])
А что будет, если юзер не найдется?

Именование не подразумевает что есть еще какая то проверка на срок давности.

2020-06-21 11:38 UTC, pn-y commented on app/models/user.rb
> +    password_reset_token_sent_at < 24.hours.ago
24 вынести в константу

2020-06-21 11:38 UTC, pn-y commented on app/models/user.rb
> +    if user && (not user.password_reset_token_expired?)
! вместо not

2020-06-21 11:38 UTC, pn-y commented on app/models/user.rb
> +    SecureRandom.urlsafe_base64
а если уже существует такой токен?

2020-06-21 11:38 UTC, pn-y commented on db/migrate/20200621070208_add_reset_passwd.rb
> +    add_column :users, :password_reset_token, :string
Уникальность бы обеспечить

2020-06-23 10:22 UTC, pn-y requested changes

2020-06-23 10:22 UTC, pn-y commented on app/controllers/web/passwords_controller.rb
> +      redirect_to(:root)
redirect_to root_url

2020-06-23 10:22 UTC, pn-y commented on app/controllers/web/passwords_controller.rb
> +    if @user
Сложно получается, целый каскад из условий.
Что если сразу вернуть рендер и флеш, если юзер не найден?

2020-06-23 10:22 UTC, pn-y commented on app/models/user.rb
> +    update_attribute(:password_reset_token, User.digest(password_reset_token))
один update сделой

2020-06-23 10:22 UTC, pn-y commented on app/models/user.rb
> +    update_attribute(:password_reset_token, nil)
и тут

2020-06-23 10:22 UTC, pn-y commented on db/schema.rb
> +    t.datetime "password_reset_token_sent_at"
Тут не хватает записи об уникальном индексе

2020-06-23 16:50 UTC, xevyd commented on app/controllers/web/passwords_controller.rb
> +      redirect_to(:root)
без скобок ругается rubocop, а с _url тест падает : `undefined method `root_url_url' for Did you mean?  root_url`

2020-06-25 19:12 UTC, pn-y requested changes
Еще у тебя тесты падают. Почини.

2020-06-25 19:12 UTC, pn-y commented on app/controllers/web/passwords_controller.rb
> +      redirect_to(:root)
О, фигасе, кажись так тоже можно!
Кароч `redirect_to(:root)` это аналог `redirect_to(root_url)`
Вот оно че. Претензия снимается

2020-06-25 19:12 UTC, pn-y commented on app/controllers/web/passwords_controller.rb
> +    @user = User.find_by_password_reset_token(params[:token])
^^^

2020-06-25 19:12 UTC, pn-y commented on db/schema.rb
> +    t.datetime "password_reset_token_sent_at"
^^^

2020-06-30 19:01 UTC, pn-y requested changes

2020-06-30 19:01 UTC, pn-y commented on db/migrate/20200621070208_add_reset_passwd.rb
> +    add_column :users, :password_reset_token, :string, unique: true
Так не работает

2020-06-30 19:01 UTC, pn-y commented on db/migrate/20200622144202_reset_password_fix.rb
> +    change_column :users, :password_reset_token, :string, unique: true
И так тоже не работает

2020-06-30 19:01 UTC, pn-y commented on db/schema.rb
> +    t.datetime "password_reset_token_sent_at"
Все еще нет записи об уникальном индексе

2020-07-01 07:13 UTC, xevyd commented on db/schema.rb
> +    t.datetime "password_reset_token_sent_at"
ну какже нет, если в [этом коммите](https://github.com/xevyd/TaskManager/commit/01f04ba69a635fac8b97bdb6805fb184e81a0353) ?

2020-07-06 20:50 UTC, artempartos approved these changes

2020-07-07 05:56 UTC, merged