add state machine
xevyd/TaskManager pull request #8
Opened 2020-05-09 18:18 UTC by xevyd

2020-05-09 22:24 UTC, Andrew8xx8 requested changes

2020-05-09 22:24 UTC, Andrew8xx8 commented on app/models/task.rb
> +  state_machine initial: :new_task do
Опиши все возможные стейты в начале используя инструкцию `state`

2020-05-10 01:35 UTC, xevyd commented on app/models/task.rb
> +  state_machine initial: :new_task do
добавил

2020-05-10 08:32 UTC, Andrew8xx8 approved these changes

2020-05-10 09:15 UTC, merged